In [3]:
import numpy as np

In [4]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [11]:
#1There are 4 negative numbers 

a[a<0]

array([-2, -1, -6, -7])

In [12]:
#2 There are 5 positive numbers
a[a>0]

array([ 4, 10, 12, 23,  3])

In [ ]:
#3 There are 3 even positive numbers 

In [21]:
#4 There would be 8 positive numbers

add_three= a+3

In [6]:
# 5
np.square(a)

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [13]:
#5
b = np.array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [15]:
#5 b.std()

144.0243035046516

In [16]:
#5 b.mean()

74.0

In [5]:
#6

centered= a-a.mean()

In [6]:
centered.mean()

0.0

In [7]:
#7 

zscores= a-a.mean()/a.std()